import { useEffect, useState, useCallback, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../api/client';
import { Question } from '../types';
import OptimizedImage from '../components/OptimizedImage';
import DiagramRenderer from '../components/DiagramRenderer';

const DURATION = 15 * 60;

export default function Exam() {
  const { modelId } = useParams(); const navigate = useNavigate();
  const [questions,setQuestions]=useState<Question[]>([]); const [answers,setAnswers]=useState<Record<number,number>>({}); const [current,setCurrent]=useState(0); const [seconds,setSeconds]=useState(DURATION); const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState<string|null>(null); const [imageExpanded,setImageExpanded]=useState(false); const finishedRef=useRef(false);
  const loadExam=useCallback(async()=>{const id=Number(modelId)||1;setLoading(true);setLoadError(null);try{const picked=await api.getExamQuestions(id);if(picked.length!==30)throw new Error('تعذر تجهيز ٣٠ سؤالاً للاختبار.');setQuestions(picked);setAnswers({});setCurrent(0);setSeconds(DURATION);finishedRef.current=false;}catch(err){setLoadError(err instanceof Error?err.message:'تعذر تحميل الأسئلة.');}finally{setLoading(false);}},[modelId]);
  useEffect(()=>{void loadExam();},[loadExam]); useEffect(()=>{questions.slice(current,current+3).forEach(q=>{if(q.imageUrl){const img=new Image();img.decoding='async';img.src=q.imageUrl;}});},[questions,current]); useEffect(()=>{setImageExpanded(false);},[current]);
  const finish=useCallback(()=>{if(finishedRef.current||!questions.length)return;finishedRef.current=true;let correct=0;const reviewQuestions=questions.map(question=>{const chosen=answers[question.id];if(chosen===question.correctAnswerIndex)correct++;return{question,chosen:chosen??null};});const answered=Object.keys(answers).length;const wrongQuestionIds=reviewQuestions.filter(x=>x.chosen!==null&&x.chosen!==x.question.correctAnswerIndex).map(x=>x.question.id);api.submitExamAttempt({modelId:Number(modelId)||1,total:questions.length,correct,answered,wrongQuestionIds}).catch(()=>{});navigate('/result',{state:{correct,total:questions.length,answered,reviewQuestions,modelId:Number(modelId)||1}});},[answers,questions,navigate,modelId]);
  useEffect(()=>{if(loading)return;const timer=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(timer);finish();return 0;}return s-1;}),1000);return()=>clearInterval(timer);},[loading,finish]);
  if(loading)return <div className="page-shell flex items-center justify-center px-4"><div className="surface-panel w-full max-w-xl p-5"><div className="skeleton h-44 rounded-2xl"/><div className="skeleton h-5 rounded-lg mt-4"/><div className="skeleton h-12 rounded-xl mt-3"/><div className="skeleton h-12 rounded-xl mt-2"/></div></div>;
  if(loadError||!questions.length)return <div className="page-shell flex items-center justify-center px-5"><div className="surface-panel w-full max-w-md text-center p-7"><div className="brand-mark mx-auto mb-4">ر</div><h1 className="text-xl font-black mb-2">تعذر تحضير الاختبار</h1><p className="text-muted text-sm leading-relaxed">{loadError??'لم يتم العثور على أسئلة.'}</p><button onClick={loadExam} className="primary-cta mt-5 w-full">إعادة المحاولة</button></div></div>;
  const q=questions[current];const mm=String(Math.floor(seconds/60)).padStart(2,'0');const ss=String(seconds%60).padStart(2,'0');const answered=Object.keys(answers).length;const correct=questions.filter(x=>answers[x.id]===x.correctAnswerIndex).length;
  return <div className="exam-page">
    <header className="exam-header"><div className="max-w-6xl mx-auto px-3 sm:px-5 py-3 flex items-center gap-3"><button onClick={()=>navigate('/models')} className="icon-button" aria-label="العودة">→</button><div className="flex-1 min-w-0"><p className="eyebrow">اختبار القيادة الرسمي</p><p className="font-black text-ink text-sm">النموذج {modelId} <span className="text-muted font-normal">• ٣٠ سؤال • ١٥ دقيقة</span></p></div><div className={`exam-timer ${seconds<=60?'urgent':''}`}><span>الوقت</span>{mm}:{ss}</div></div><div className="progress"><span style={{width:`${((current+1)/questions.length)*100}%`}}/></div></header>
    <main className="max-w-6xl mx-auto w-full px-3 sm:px-5 py-3 sm:py-5"><div className="exam-layout">
      <section className="surface-panel exam-card p-3 sm:p-5"><div className="flex items-center justify-between gap-3 mb-3"><span className="question-number">السؤال {current+1} من {questions.length}</span><span className="text-xs text-muted">أجبت {answered} • صحيح {correct}</span></div>
        {q.imageUrl&&<div className="exam-image-frame"><OptimizedImage src={q.imageUrl} alt={`صورة السؤال ${q.id}`} priority={current===0} sizes="(max-width: 900px) 94vw, 700px" className="w-full h-full object-contain"/><button type="button" onClick={()=>setImageExpanded(true)} className="image-expand" aria-label="تكبير الصورة">+</button></div>}
        <h1 className="exam-question-title">{q.text}</h1><div className="exam-answer-grid">{q.options.map((opt,i)=><button key={i} onClick={()=>setAnswers(a=>({...a,[q.id]:i}))} className={`answer-option ${answers[q.id]===i?'selected':''}`}><span className="answer-letter">{['أ','ب','ج','د','هـ','و'][i]}</span><span className="flex-1 leading-relaxed text-right">{opt}</span></button>)}</div><DiagramRenderer question={q}/><div className="flex gap-2 mt-4"><button onClick={()=>setCurrent(c=>Math.max(c-1,0))} disabled={current===0} className="secondary-cta flex-1 py-3">السابق</button><button onClick={()=>setCurrent(c=>Math.min(c+1,questions.length-1))} disabled={current===questions.length-1} className="primary-cta flex-1 py-3 disabled:opacity-40">التالي ←</button></div>
      </section>
      <aside className="surface-panel exam-sidebar p-4"><div className="sidebar-title"><div><p className="eyebrow">ورقة الإجابة</p><h2>تنقّل بين الأسئلة</h2></div><b>{answered}/30</b></div><div className="exam-grid">{questions.map((qq,i)=><button key={qq.id} onClick={()=>setCurrent(i)} className={`exam-index ${i===current?'current':answers[qq.id]!==undefined?'answered':''}`}>{i+1}</button>)}</div><div className="legend"><span><i className="current"/> الحالي</span><span><i className="answered"/> مجاب</span><span><i/> غير مجاب</span></div><div className="mt-5 p-3 rounded-2xl bg-exam-soft border border-exam/20"><p className="text-xs text-exam font-bold">ملاحظة</p><p className="text-xs text-muted mt-1 leading-relaxed">النجاح يحتاج ٢٥ إجابة صحيحة من أصل ٣٠.</p></div><button onClick={finish} className="finish-button">إنهاء الاختبار وعرض النتيجة</button></aside>
    </div></main>
    {imageExpanded&&q.imageUrl&&<div className="fixed inset-0 z-[100] bg-black/85 backdrop-blur-sm flex items-center justify-center p-3" onClick={()=>setImageExpanded(false)}><div className="relative w-full h-full flex items-center justify-center"><OptimizedImage src={q.imageUrl} alt={`الصورة المكبرة للسؤال ${q.id}`} sizes="100vw" className="max-w-full max-h-full object-contain rounded-xl"/><button onClick={()=>setImageExpanded(false)} className="absolute top-2 right-2 w-10 h-10 rounded-full bg-black/70 text-white text-xl">×</button></div></div>}
  </div>;
}
