using System.Text.Json;
using DrivingTestApi.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace DrivingTestApi.Data;

public static class DbSeeder
{
    public static async Task SeedAsync(IServiceProvider services)
    {
        var db = services.GetRequiredService<AppDbContext>();

        var tablesExist = true;

        try
        {
            await db.Database.ExecuteSqlRawAsync(
                "SELECT 1 FROM \"AspNetRoles\" LIMIT 1");
        }
        catch
        {
            tablesExist = false;
        }

        if (!tablesExist)
        {
            var createScript = db.Database.GenerateCreateScript();
            await db.Database.ExecuteSqlRawAsync(createScript);
        }

        if (tablesExist)
        {
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramType\" text NULL;");

            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramUrl\" text NULL;");

            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramTitle\" text NULL;");

            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramDescription\" text NULL;");

            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS \"ExamResults\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"UserId\" text NULL, \"ModelId\" integer NOT NULL, \"Total\" integer NOT NULL, \"Correct\" integer NOT NULL, \"Answered\" integer NOT NULL, \"Passed\" boolean NOT NULL, \"CreatedAt\" timestamp with time zone NOT NULL);");

            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_ExamResults_UserId\" ON \"ExamResults\" (\"UserId\");");

            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS \"ExamAttempts\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"StudentId\" text NOT NULL, \"ModelId\" integer NOT NULL, \"Correct\" integer NOT NULL, \"Total\" integer NOT NULL, \"Answered\" integer NOT NULL, \"WrongQuestionIds\" text NOT NULL, \"CreatedAt\" timestamp with time zone NOT NULL);");

            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_ExamAttempts_StudentId_CreatedAt\" ON \"ExamAttempts\" (\"StudentId\", \"CreatedAt\");");
        }

        var roleManager =
            services.GetRequiredService<RoleManager<IdentityRole>>();

        foreach (var role in new[] { "Admin", "Student" })
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole(role));
            }
        }

        var userManager =
            services.GetRequiredService<UserManager<ApplicationUser>>();

        var config =
            services.GetRequiredService<IConfiguration>();

        var adminUserName = config["SeedAdmin:UserName"];
        var adminPassword = config["SeedAdmin:Password"];

        if (!string.IsNullOrEmpty(adminUserName) &&
            !string.IsNullOrEmpty(adminPassword))
        {
            var existingAdmin =
                await userManager.FindByNameAsync(adminUserName);

            if (existingAdmin is null)
            {
                var admin = new ApplicationUser
                {
                    UserName = adminUserName,
                    FullName = "Admin",
                    IsActive = true,
                    EmailConfirmed = true
                };

                var result =
                    await userManager.CreateAsync(admin, adminPassword);

                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(admin, "Admin");
                }
            }
        }

        // أولاً نضيف الأسئلة الناقصة.
        await SeedQuestionsAsync(db);

        // بعدها نصحح جميع صور الميكانيك.
        // هذا مهم حتى الصور المضافة حديثاً من questions.json
        // يتم تحويلها أيضاً.
        await NormalizeQuestionImagesAsync(db);

        // وأخيراً نصلح الأسئلة غير المكتملة.
        await RepairIncompleteQuestionsAsync(db);
    }

    private static async Task NormalizeQuestionImagesAsync(AppDbContext db)
    {
        var existing = await db.Questions.ToListAsync();

        if (existing.Count == 0)
            return;

        var path = Path.Combine(
            AppContext.BaseDirectory,
            "Data",
            "SeedData",
            "questions.json");

        var items = new List<SeedQuestion>();

        // questions.json اختياري هنا.
        // تحويل صور الميكانيك يجب أن يعمل حتى لو لم يوجد الملف.
        if (File.Exists(path))
        {
            var json = await File.ReadAllTextAsync(path);

            items =
                JsonSerializer.Deserialize<List<SeedQuestion>>(
                    json,
                    new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    })
                ?? new List<SeedQuestion>();
        }

        static string QuestionContentSignature(Question q)
        {
            return string.Join(
                "|",
                q.Category,
                q.Text,
                string.Join("\u001f", q.Options));
        }

        static string SeedContentSignature(
            SeedQuestion q,
            QuestionCategory category)
        {
            return string.Join(
                "|",
                category,
                q.Text,
                string.Join(
                    "\u001f",
                    q.Options ?? new List<string>()));
        }

        var seedByContent = items
            .Select(x =>
            {
                Enum.TryParse<QuestionCategory>(
                    x.Category,
                    true,
                    out var category);

                return new
                {
                    x,
                    category
                };
            })
            .Where(x => !string.IsNullOrWhiteSpace(x.x.Text))
            .GroupBy(x =>
                SeedContentSignature(x.x, x.category))
            .ToDictionary(
                g => g.Key,
                g => g.Select(x => x.x).ToList(),
                StringComparer.Ordinal);

        var changed = false;

        foreach (var q in existing)
        {
            if (q.Category == QuestionCategory.Mechanic &&
                !string.IsNullOrWhiteSpace(q.ImageUrl))
            {
                var file =
                    Path.GetFileNameWithoutExtension(q.ImageUrl);

                // مثال:
                // /signs/sign_222.webp
                //       ↓
                // /mechanic/mechanic_222.webp
                //
                // يعمل مع أي رقم، وليس فقط 210-235.
                if (file.StartsWith(
                        "sign_",
                        StringComparison.OrdinalIgnoreCase) &&
                    int.TryParse(
                        file[5..],
                        out var mechanicNumber))
                {
                    var normalized =
                        $"/mechanic/mechanic_{mechanicNumber}.webp";

                    if (!string.Equals(
                            q.ImageUrl,
                            normalized,
                            StringComparison.OrdinalIgnoreCase))
                    {
                        q.ImageUrl = normalized;
                        changed = true;
                    }
                }
            }
            else if (
                q.Category != QuestionCategory.Mechanic &&
                !string.IsNullOrWhiteSpace(q.ImageUrl))
            {
                var file =
                    Path.GetFileNameWithoutExtension(q.ImageUrl);

                if (file.StartsWith(
                        "sign_",
                        StringComparison.OrdinalIgnoreCase) &&
                    int.TryParse(
                        file[5..],
                        out var signNumber))
                {
                    if ((signNumber >= 1 && signNumber <= 131) ||
                        (signNumber >= 200 && signNumber <= 205))
                    {
                        var normalized =
                            signNumber < 100
                                ? $"/signs/sign_{signNumber:00}.webp"
                                : $"/signs/sign_{signNumber}.webp";

                        if (!string.Equals(
                                q.ImageUrl,
                                normalized,
                                StringComparison.OrdinalIgnoreCase))
                        {
                            q.ImageUrl = normalized;
                            changed = true;
                        }
                    }
                }
            }

            // إذا كان السؤال بدون صورة،
            // نحاول أخذ الصورة من questions.json.
            if (string.IsNullOrWhiteSpace(q.ImageUrl) &&
                seedByContent.TryGetValue(
                    QuestionContentSignature(q),
                    out var matches) &&
                matches.Count == 1 &&
                !string.IsNullOrWhiteSpace(
                    matches[0].ImageUrl))
            {
                q.ImageUrl = matches[0].ImageUrl;
                changed = true;

                // إذا كانت الصورة الموجودة في JSON
                // هي sign_XXX والسؤال Mechanic،
                // نحولها مباشرة إلى mechanic_XXX.
                if (q.Category == QuestionCategory.Mechanic &&
                    !string.IsNullOrWhiteSpace(q.ImageUrl))
                {
                    var seedFile =
                        Path.GetFileNameWithoutExtension(
                            q.ImageUrl);

                    if (seedFile.StartsWith(
                            "sign_",
                            StringComparison.OrdinalIgnoreCase) &&
                        int.TryParse(
                            seedFile[5..],
                            out var mechanicNumber))
                    {
                        q.ImageUrl =
                            $"/mechanic/mechanic_{mechanicNumber}.webp";
                    }
                }
            }
        }

        if (changed)
        {
            await db.SaveChangesAsync();
        }
    }

    private static async Task RepairIncompleteQuestionsAsync(
        AppDbContext db)
    {
        var existing =
            await db.Questions
                .OrderBy(q => q.Id)
                .ToListAsync();

        if (existing.Count == 0)
            return;

        var incomplete = existing
            .Where(q =>
                string.IsNullOrWhiteSpace(q.Text) ||
                q.Options.Count < 2 ||
                q.Options.Any(string.IsNullOrWhiteSpace) ||
                IsBrokenMechanicImage(q))
            .ToList();

        // حتى لو لم توجد أسئلة ناقصة،
        // نصحح صور الميكانيك الموجودة.
        var mechanicImagesChanged = false;

        foreach (var q in existing)
        {
            if (q.Category != QuestionCategory.Mechanic ||
                string.IsNullOrWhiteSpace(q.ImageUrl))
            {
                continue;
            }

            var file =
                Path.GetFileNameWithoutExtension(q.ImageUrl);

            if (file.StartsWith(
                    "sign_",
                    StringComparison.OrdinalIgnoreCase) &&
                int.TryParse(
                    file[5..],
                    out var mechanicNumber))
            {
                var normalized =
                    $"/mechanic/mechanic_{mechanicNumber}.webp";

                if (!string.Equals(
                        q.ImageUrl,
                        normalized,
                        StringComparison.OrdinalIgnoreCase))
                {
                    q.ImageUrl = normalized;
                    mechanicImagesChanged = true;
                }
            }
        }

        if (mechanicImagesChanged)
        {
            await db.SaveChangesAsync();
        }

        if (incomplete.Count == 0)
            return;

        var path = Path.Combine(
            AppContext.BaseDirectory,
            "Data",
            "SeedData",
            "questions.json");

        if (!File.Exists(path))
            return;

        var json = await File.ReadAllTextAsync(path);

        var items =
            JsonSerializer.Deserialize<List<SeedQuestion>>(
                json,
                new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                })
            ?? new List<SeedQuestion>();

        var byKey = items
            .Select((x, index) => new
            {
                x,
                index
            })
            .ToDictionary(
                x => $"{x.x.Category}|{x.x.Text}",
                x => x.x,
                StringComparer.Ordinal);

        foreach (var q in incomplete)
        {
            SeedQuestion? seed = null;

            if (!string.IsNullOrWhiteSpace(q.Text))
            {
                byKey.TryGetValue(
                    $"{q.Category}|{q.Text}",
                    out seed);
            }

            if (seed is null &&
                items.Count == existing.Count &&
                q.Id >= 1 &&
                q.Id <= items.Count)
            {
                seed = items[q.Id - 1];
            }

            if (seed is not null &&
                seed.Options.Count >= 2 &&
                (q.Options.Count < 2 ||
                 q.Options.Any(string.IsNullOrWhiteSpace) ||
                 string.IsNullOrWhiteSpace(q.Text)))
            {
                q.Text = seed.Text;

                q.Category =
                    Enum.TryParse<QuestionCategory>(
                        seed.Category,
                        true,
                        out var category)
                        ? category
                        : q.Category;

                q.Options = seed.Options;

                q.CorrectAnswerIndex =
                    Math.Clamp(
                        seed.CorrectAnswerIndex,
                        0,
                        seed.Options.Count - 1);

                q.Explanation = seed.Explanation;

                if (string.IsNullOrWhiteSpace(q.ImageUrl))
                {
                    q.ImageUrl = seed.ImageUrl;
                }

                q.DiagramType = seed.DiagramType;
                q.DiagramUrl = seed.DiagramUrl;
                q.DiagramTitle = seed.DiagramTitle;
                q.DiagramDescription =
                    seed.DiagramDescription;
            }

            // أي sign_XXX داخل سؤال Mechanic
            // يتحول إلى mechanic_XXX.
            if (q.Category == QuestionCategory.Mechanic &&
                !string.IsNullOrWhiteSpace(q.ImageUrl))
            {
                var file =
                    Path.GetFileNameWithoutExtension(q.ImageUrl);

                if (file.StartsWith(
                        "sign_",
                        StringComparison.OrdinalIgnoreCase) &&
                    int.TryParse(
                        file[5..],
                        out var n))
                {
                    q.ImageUrl =
                        $"/mechanic/mechanic_{n}.webp";
                }
            }
        }

        await db.SaveChangesAsync();
    }

    private static bool IsBrokenMechanicImage(Question q)
    {
        if (q.Category != QuestionCategory.Mechanic)
            return false;

        if (string.IsNullOrWhiteSpace(q.ImageUrl))
            return false;

        var file =
            Path.GetFileNameWithoutExtension(q.ImageUrl);

        return file.StartsWith(
                   "sign_",
                   StringComparison.OrdinalIgnoreCase) &&
               int.TryParse(
                   file[5..],
                   out _);
    }

    private static async Task SeedQuestionsAsync(
        AppDbContext db)
    {
        var path = Path.Combine(
            AppContext.BaseDirectory,
            "Data",
            "SeedData",
            "questions.json");

        if (!File.Exists(path))
            return;

        var json =
            await File.ReadAllTextAsync(path);

        var items =
            JsonSerializer.Deserialize<List<SeedQuestion>>(
                json,
                new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });

        if (items is null || items.Count == 0)
            return;

        static string ExistingQuestionSignature(Question q)
        {
            return string.Join(
                "|",
                q.Category,
                q.Text,
                string.Join("\u001f", q.Options),
                q.ImageUrl ?? string.Empty,
                q.DiagramType ?? string.Empty,
                q.DiagramUrl ?? string.Empty);
        }

        static string SeedQuestionSignature(
            SeedQuestion q,
            QuestionCategory category)
        {
            return string.Join(
                "|",
                category,
                q.Text,
                string.Join(
                    "\u001f",
                    q.Options ?? new List<string>()),
                q.ImageUrl ?? string.Empty,
                q.DiagramType ?? string.Empty,
                q.DiagramUrl ?? string.Empty);
        }

        var existingSignatures =
            (await db.Questions
                .AsNoTracking()
                .ToListAsync())
            .Select(ExistingQuestionSignature)
            .ToHashSet(StringComparer.Ordinal);

        var added = 0;

        foreach (var item in items)
        {
            if (!Enum.TryParse<QuestionCategory>(
                    item.Category,
                    true,
                    out var category))
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(item.Text))
                continue;

            if (item.Options is null ||
                item.Options.Count < 2)
            {
                continue;
            }

            if (item.CorrectAnswerIndex < 0 ||
                item.CorrectAnswerIndex >= item.Options.Count)
            {
                continue;
            }

            var signature =
                SeedQuestionSignature(item, category);

            if (existingSignatures.Contains(signature))
                continue;

            var imageUrl = item.ImageUrl;

            // إذا كان السؤال Mechanic والصورة
            // موجودة بصيغة sign_XXX، نستخدم صورة mechanic_XXX.
            if (category == QuestionCategory.Mechanic &&
                !string.IsNullOrWhiteSpace(imageUrl))
            {
                var file =
                    Path.GetFileNameWithoutExtension(imageUrl);

                if (file.StartsWith(
                        "sign_",
                        StringComparison.OrdinalIgnoreCase) &&
                    int.TryParse(
                        file[5..],
                        out var mechanicNumber))
                {
                    imageUrl =
                        $"/mechanic/mechanic_{mechanicNumber}.webp";
                }
            }

            db.Questions.Add(new Question
            {
                Category = category,
                Text = item.Text,
                Options = item.Options,
                CorrectAnswerIndex =
                    item.CorrectAnswerIndex,
                Explanation = item.Explanation,
                ImageUrl = imageUrl,
                DiagramType = item.DiagramType,
                DiagramUrl = item.DiagramUrl,
                DiagramTitle = item.DiagramTitle,
                DiagramDescription =
                    item.DiagramDescription
            });

            existingSignatures.Add(signature);
            added++;
        }

        if (added > 0)
        {
            await db.SaveChangesAsync();
        }
    }

    private class SeedQuestion
    {
        public string Category { get; set; } = "";
        public string Text { get; set; } = "";
        public List<string> Options { get; set; } = new ();
        public int CorrectAnswerIndex { get; set; }
        public string? Explanation { get; set; }
        public string? ImageUrl { get; set; }
        public string? DiagramType { get; set; }
        public string? DiagramUrl { get; set; }
        public string? DiagramTitle { get; set; }
        public string? DiagramDescription { get; set; }
    }
}