using System.Text.Json;
using DrivingTestApi.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace DrivingTestApi.Data;

public static class DbSeeder
{
    public static async Task SeedAsync(IServiceProvider services)
    {
        var db = services.GetRequiredService<AppDbContext>();
        // نتحقق فعلياً من وجود الجداول (لا نكتفي بالتحقق من وجود قاعدة البيانات نفسها،
        // لأن قاعدة postgres على Supabase موجودة دائماً بشكل افتراضي بغض النظر عن الجداول).
        var tablesExist = true;
        try
        {
            await db.Database.ExecuteSqlRawAsync("SELECT 1 FROM \"AspNetRoles\" LIMIT 1");
        }
        catch
        {
            tablesExist = false;
        }

        if (!tablesExist)
        {
            var createScript = db.Database.GenerateCreateScript();
            await db.Database.ExecuteSqlRawAsync(createScript);
        }

        // Compatibility upgrades for existing databases. These are idempotent and avoid
        // requiring a manual migration just to enable diagrams and exam analytics.
        if (tablesExist)
        {
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramType\" text NULL;");
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramUrl\" text NULL;");
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramTitle\" text NULL;");
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Questions\" ADD COLUMN IF NOT EXISTS \"DiagramDescription\" text NULL;");
            await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS \"ExamResults\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"UserId\" text NULL, \"ModelId\" integer NOT NULL, \"Total\" integer NOT NULL, \"Correct\" integer NOT NULL, \"Answered\" integer NOT NULL, \"Passed\" boolean NOT NULL, \"CreatedAt\" timestamp with time zone NOT NULL);");
            await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_ExamResults_UserId\" ON \"ExamResults\" (\"UserId\");");
        }

        var roleManager = services.GetRequiredService<RoleManager<IdentityRole>>();
        foreach (var role in new[] { "Admin", "Student" })
        {
            if (!await roleManager.RoleExistsAsync(role))
                await roleManager.CreateAsync(new IdentityRole(role));
        }

        // حساب الأدمن الأول يُنشأ من متغيرات البيئة SeedAdmin__UserName / SeedAdmin__Password
        // فقط عند أول تشغيل — وليس مكتوباً بالكود إطلاقاً.
        var userManager = services.GetRequiredService<UserManager<ApplicationUser>>();
        var config = services.GetRequiredService<IConfiguration>();

        var adminUserName = config["SeedAdmin:UserName"];
        var adminPassword = config["SeedAdmin:Password"];

        if (!string.IsNullOrEmpty(adminUserName) && !string.IsNullOrEmpty(adminPassword))
        {
            var existingAdmin = await userManager.FindByNameAsync(adminUserName);
            if (existingAdmin is null)
            {
                var admin = new ApplicationUser
                {
                    UserName = adminUserName,
                    FullName = "Admin",
                    IsActive = true,
                    EmailConfirmed = true
                };

                var result = await userManager.CreateAsync(admin, adminPassword);
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(admin, "Admin");
                }
            }
        }

        await SeedQuestionsAsync(db);
        await RepairIncompleteQuestionsAsync(db);
    }

    // يصلّح فقط الأسئلة الموجودة مسبقاً إذا كانت الاختيارات مفقودة/ناقصة بسبب إصدار سابق.
    // لا يلمس الأسئلة السليمة ولا يعيد الكتابة على تعديلات الأدمن.
    private static async Task RepairIncompleteQuestionsAsync(AppDbContext db)
    {
        // ValueConverter يجعل Options عموداً نصياً، لذلك نفحص القائمة بعد تحميلها إلى الذاكرة
        // ولا نعتمد على ترجمة Count/Any إلى SQL.
        var existing = await db.Questions.OrderBy(q => q.Id).ToListAsync();
        if (existing.Count == 0) return;

        var mechanicImageNeedsRepair = (Question q) =>
            q.Category == QuestionCategory.Mechanic &&
            !string.IsNullOrWhiteSpace(q.ImageUrl) &&
            q.ImageUrl.StartsWith("/signs/sign_", StringComparison.OrdinalIgnoreCase) &&
            int.TryParse(Path.GetFileNameWithoutExtension(q.ImageUrl).Replace("sign_", "", StringComparison.OrdinalIgnoreCase), out var n) &&
            n >= 210 && n <= 235;

        var incomplete = existing
            .Where(q => string.IsNullOrWhiteSpace(q.Text)
                || q.Options.Count < 2
                || q.Options.Any(string.IsNullOrWhiteSpace)
                || mechanicImageNeedsRepair(q))
            .ToList();

        if (incomplete.Count == 0) return;

        var path = Path.Combine(AppContext.BaseDirectory, "Data", "SeedData", "questions.json");
        if (!File.Exists(path)) return;

        var json = await File.ReadAllTextAsync(path);
        var items = JsonSerializer.Deserialize<List<SeedQuestion>>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        }) ?? new List<SeedQuestion>();

        var byKey = items
            .Select((x, index) => new { x, index })
            .ToDictionary(
                x => $"{x.x.Category}|{x.x.Text}",
                x => x.x,
                StringComparer.Ordinal);

        foreach (var q in incomplete)
        {
            SeedQuestion? seed = null;
            if (!string.IsNullOrWhiteSpace(q.Text))
                byKey.TryGetValue($"{q.Category}|{q.Text}", out seed);

            if (seed is null && items.Count == existing.Count && q.Id >= 1 && q.Id <= items.Count)
                seed = items[q.Id - 1];

            if (seed is not null && seed.Options.Count >= 2 &&
                (q.Options.Count < 2 || q.Options.Any(string.IsNullOrWhiteSpace) || string.IsNullOrWhiteSpace(q.Text)))
            {
                q.Text = seed.Text;
                q.Category = Enum.TryParse<QuestionCategory>(seed.Category, true, out var category) ? category : q.Category;
                q.Options = seed.Options;
                q.CorrectAnswerIndex = Math.Clamp(seed.CorrectAnswerIndex, 0, seed.Options.Count - 1);
                q.Explanation = seed.Explanation;
                if (string.IsNullOrWhiteSpace(q.ImageUrl)) q.ImageUrl = seed.ImageUrl;
                q.DiagramType = seed.DiagramType;
                q.DiagramUrl = seed.DiagramUrl;
                q.DiagramTitle = seed.DiagramTitle;
                q.DiagramDescription = seed.DiagramDescription;
            }

            // تحويل صور الميكانيك القديمة إلى النسخة المقصوصة والواضحة الجديدة، حتى
            // قواعد البيانات الموجودة مسبقاً تستفيد من الصور المحسنة بدون إعادة زرع كاملة.
            if (q.Category == QuestionCategory.Mechanic && !string.IsNullOrWhiteSpace(q.ImageUrl))
            {
                var file = Path.GetFileNameWithoutExtension(q.ImageUrl);
                if (file.StartsWith("sign_", StringComparison.OrdinalIgnoreCase) &&
                    int.TryParse(file[5..], out var n) && n >= 210 && n <= 235)
                    q.ImageUrl = $"/mechanic/mechanic_{n}.webp";
            }
        }

        await db.SaveChangesAsync();
    }

    // يزرع بنك الأسئلة الكامل (٣٤٧ سؤال: سير + إشارات + ميكانيك) من ملف JSON مرفق بالمشروع،
    // مرة واحدة فقط — إذا كان جدول الأسئلة فارغاً. تعديل الأسئلة لاحقاً يكون من قاعدة البيانات مباشرة.
    private static async Task SeedQuestionsAsync(AppDbContext db)
    {
        if (await db.Questions.AnyAsync()) return;

        var path = Path.Combine(AppContext.BaseDirectory, "Data", "SeedData", "questions.json");
        if (!File.Exists(path)) return;

        var json = await File.ReadAllTextAsync(path);
        var items = JsonSerializer.Deserialize<List<SeedQuestion>>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        });

        if (items is null) return;

        foreach (var item in items)
        {
            if (!Enum.TryParse<QuestionCategory>(item.Category, true, out var category)) continue;

            db.Questions.Add(new Question
            {
                Category = category,
                Text = item.Text,
                Options = item.Options,
                CorrectAnswerIndex = item.CorrectAnswerIndex,
                Explanation = item.Explanation,
                ImageUrl = item.ImageUrl,
                DiagramType = item.DiagramType,
                DiagramUrl = item.DiagramUrl,
                DiagramTitle = item.DiagramTitle,
                DiagramDescription = item.DiagramDescription
            });
        }

        await db.SaveChangesAsync();
    }

    private class SeedQuestion
    {
        public string Category { get; set; } = "";
        public string Text { get; set; } = "";
        public List<string> Options { get; set; } = new();
        public int CorrectAnswerIndex { get; set; }
        public string? Explanation { get; set; }
        public string? ImageUrl { get; set; }
        public string? DiagramType { get; set; }
        public string? DiagramUrl { get; set; }
        public string? DiagramTitle { get; set; }
        public string? DiagramDescription { get; set; }
    }
}

