using System.Text.Json;
using DrivingTestApi.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace DrivingTestApi.Data;

public static class DbSeeder
{
    public static async Task SeedAsync(IServiceProvider services)
    {
        var db = services.GetRequiredService<AppDbContext>();
        // نتحقق فعلياً من وجود الجداول (لا نكتفي بالتحقق من وجود قاعدة البيانات نفسها،
        // لأن قاعدة postgres على Supabase موجودة دائماً بشكل افتراضي بغض النظر عن الجداول).
        var tablesExist = true;
        try
        {
            await db.Database.ExecuteSqlRawAsync("SELECT 1 FROM \"AspNetRoles\" LIMIT 1");
        }
        catch
        {
            tablesExist = false;
        }

        if (!tablesExist)
        {
            var createScript = db.Database.GenerateCreateScript();
            await db.Database.ExecuteSqlRawAsync(createScript);
        }

        // Compatibility upgrades for existing databases. All statements are idempotent:
        // old installations keep their data and gain the new diagram + attempt features.
        await db.Database.ExecuteSqlRawAsync("""
ALTER TABLE "Questions" ADD COLUMN IF NOT EXISTS "DiagramType" text NULL;
ALTER TABLE "Questions" ADD COLUMN IF NOT EXISTS "DiagramUrl" text NULL;
ALTER TABLE "Questions" ADD COLUMN IF NOT EXISTS "DiagramTitle" text NULL;
ALTER TABLE "Questions" ADD COLUMN IF NOT EXISTS "DiagramDescription" text NULL;

CREATE TABLE IF NOT EXISTS "ExamResults" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" text NULL,
    "ModelId" integer NOT NULL,
    "Total" integer NOT NULL,
    "Correct" integer NOT NULL,
    "Answered" integer NOT NULL,
    "Passed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ExamResults_UserId" ON "ExamResults" ("UserId");

CREATE TABLE IF NOT EXISTS "ExamAttempts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" text NOT NULL,
    "ModelId" integer NOT NULL,
    "Correct" integer NOT NULL,
    "Total" integer NOT NULL,
    "Answered" integer NOT NULL,
    "WrongQuestionIds" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ExamAttempts_StudentId_CreatedAt"
    ON "ExamAttempts" ("StudentId", "CreatedAt");
""");

        var roleManager = services.GetRequiredService<RoleManager<IdentityRole>>();
        foreach (var role in new[] { "Admin", "Student" })
        {
            if (!await roleManager.RoleExistsAsync(role))
                await roleManager.CreateAsync(new IdentityRole(role));
        }

        // حساب الأدمن الأول يُنشأ من متغيرات البيئة SeedAdmin__UserName / SeedAdmin__Password
        // فقط عند أول تشغيل — وليس مكتوباً بالكود إطلاقاً.
        var userManager = services.GetRequiredService<UserManager<ApplicationUser>>();
        var config = services.GetRequiredService<IConfiguration>();

        var adminUserName = config["SeedAdmin:UserName"];
        var adminPassword = config["SeedAdmin:Password"];

        if (!string.IsNullOrEmpty(adminUserName) && !string.IsNullOrEmpty(adminPassword))
        {
            var existingAdmin = await userManager.FindByNameAsync(adminUserName);
            if (existingAdmin is null)
            {
                var admin = new ApplicationUser
                {
                    UserName = adminUserName,
                    FullName = "Admin",
                    IsActive = true,
                    EmailConfirmed = true
                };

                var result = await userManager.CreateAsync(admin, adminPassword);
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(admin, "Admin");
                }
            }
        }

        await SeedQuestionsAsync(db);
    }

    // يزرع بنك الأسئلة من ملف JSON بشكل غير هدّام. إذا كانت القاعدة تحتوي أسئلة قديمة،
    // تتم إضافة الأسئلة الجديدة فقط دون حذف أو تكرار المحتوى الموجود.
    private static async Task SeedQuestionsAsync(AppDbContext db)
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Data", "SeedData", "questions.json");
        if (!File.Exists(path)) return;

        var json = await File.ReadAllTextAsync(path);
        var items = JsonSerializer.Deserialize<List<SeedQuestion>>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        });

        if (items is null) return;

        var existingTexts = await db.Questions
            .AsNoTracking()
            .Select(q => q.Text)
            .ToHashSetAsync();

        var added = 0;
        foreach (var item in items)
        {
            if (!Enum.TryParse<QuestionCategory>(item.Category, true, out var category)) continue;
            if (string.IsNullOrWhiteSpace(item.Text) || existingTexts.Contains(item.Text)) continue;
            if (item.Options is null || item.Options.Count < 2 ||
                item.CorrectAnswerIndex < 0 || item.CorrectAnswerIndex >= item.Options.Count) continue;

            db.Questions.Add(new Question
            {
                Category = category,
                Text = item.Text,
                Options = item.Options,
                CorrectAnswerIndex = item.CorrectAnswerIndex,
                Explanation = item.Explanation,
                ImageUrl = item.ImageUrl,
                DiagramType = item.DiagramType,
                DiagramUrl = item.DiagramUrl,
                DiagramTitle = item.DiagramTitle,
                DiagramDescription = item.DiagramDescription
            });
            existingTexts.Add(item.Text);
            added++;
        }

        if (added > 0)
            await db.SaveChangesAsync();
    }

    private class SeedQuestion
    {
        public string Category { get; set; } = "";
        public string Text { get; set; } = "";
        public List<string> Options { get; set; } = new();
        public int CorrectAnswerIndex { get; set; }
        public string? Explanation { get; set; }
        public string? ImageUrl { get; set; }
        public string? DiagramType { get; set; }
        public string? DiagramUrl { get; set; }
        public string? DiagramTitle { get; set; }
        public string? DiagramDescription { get; set; }
    }
}

