namespace DrivingTestApi.Models;

public sealed class QuestionAiImage
{
    public int QuestionId { get; set; }
    public byte[] ImageBytes { get; set; } = Array.Empty<byte>();
    public string ContentHash { get; set; } = string.Empty;
    // SHA-256 of the actual generated bytes. Used to reject an identical image
    // being assigned to more than one question.
    public string ImageHash { get; set; } = string.Empty;
    public string ContentType { get; set; } = "image/png";
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

public enum AiImageReviewStatus
{
    Pending = 0,
    Approved = 1,
    Rejected = 2
}

public sealed class AiImageReview
{
    public int QuestionId { get; set; }
    public string ContentHash { get; set; } = string.Empty;
    public AiImageReviewStatus Status { get; set; } = AiImageReviewStatus.Pending;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? ReviewedAt { get; set; }
}